name: fairmq-ex-copypush-sink
control:
  mode: fairmq
wants:
  cpu: 0.1
  memory: 128
bind: []
properties:
  severity: trace
  color: false
command:
  env: []
  log: "{{ log_task_output }}"
  shell: true
  user: flp
  arguments: []
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load FairMQ Control-OCCPlugin &&
    fairmq-ex-copypush-sink
