name: fairmq-ex-multiple-channels-broadcaster
defaults:
  log_task_output: none
control:
  mode: fairmq
wants:
  cpu: 0.1
  memory: 128
bind:
- name: "broadcast"
  type: "pub"
  sndBufSize: 1000
  rcvBufSize: 1000
  rateLogging: 0
properties:
  severity: trace
  color: false
command:
  env: []
  log: "{{ log_task_output }}"
  shell: true
  user: flp
  arguments: []
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load FairMQ Control-OCCPlugin &&
    fairmq-ex-multiple-channels-broadcaster
