name: fairmq-ex-copypush-sampler
control:
  mode: fairmq
wants:
  cpu: 0.1
  memory: 128
bind:
- name: "data"
  type: "push"
  sndBufSize: 1000
  rcvBufSize: 1000
  rateLogging: 0
properties:
  severity: trace
  color: false
command:
  env: []
  shell: true
  arguments: []
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load FairMQ &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load Control-OCCPlugin &&
    fairmq-ex-copypush-sampler
