name: internal-dpl-global-binary-file-sink
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind: []
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load QualityControl &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load Control-OCCPlugin &&
    MODULEPATH=/opt/alisw/el7/modulefiles module list &&
    o2-qc-run-readout -b | o2-qc-run-qc --config json:///etc/flp.d/qc/readout.json | o2-qc-run-readout
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "no-op://"
    - "--id"
    - "internal-dpl-global-binary-file-sink"
    - "--log-color"
    - "false"
    - "--outfile"
    - "/tmp/dpl-out.bin"
