name: mft-raw-qc-QC-CHECK-RUNNER-BasicReadoutHeaderQcCheck
defaults:
  log_task_output: none
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_QC-CHECK-RUNNER-BasicReadoutHeaderQcCheck_to_internal-dpl-injected-dummy-sink
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
command:
  shell: true
  log: "{{ log_task_output }}"
  user: "{{ user }}"
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    {{ dpl_command }} | o2-qc
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'default'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--shm-segment-size"
    - "'{{ shm_segment_size }}'"
    - "--shm-throw-bad-alloc"
    - "'{{ shm_throw_bad_alloc }}'"
    - "--id"
    - "'QC-CHECK-RUNNER-BasicReadoutHeaderQcCheck'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--config"
    - "'{{ qc_config_uri }}'"
    - "--fairmq-ipc-prefix"
    - "'/tmp'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'4'"
    - "--fairmq-send-buffer-size"
    - "'4'"
    - "--forwarding-destination"
    - "'drop'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--host"
    - "''"
    - "--pipeline"
    - "''"
    - "--readers"
    - "'1'"
    - "--severity"
    - "'info'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-zero-segment"
    - "'false'"
    - "--stacktrace-on-signal"
    - "'all'"
    - "--workflow-suffix"
    - "''"
