<<<<<<< HEAD:tasks/mid-full-qcmn-local-QcTaskMIDRaw-proxy.yaml
name: mid-full-qcmn-local-QcTaskMIDRaw-proxy
=======
name: cpv-noise-calib-qc-internal-dpl-injected-dummy-sink
>>>>>>> 27dbe988... Cpv noise calibration (#265):tasks/cpv-noise-calib-qc-internal-dpl-injected-dummy-sink.yaml
defaults:
  log_task_output: none
  exit_transition_timeout: 15
  _module_cmdline: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
<<<<<<< HEAD:tasks/mid-full-qcmn-local-QcTaskMIDRaw-proxy.yaml
    {{ dpl_command }} | o2-qc
  _plain_cmdline: >-
    source /etc/profile.d/o2.sh && {{ len(extra_env_vars)>0 ? 'export ' + extra_env_vars + ' &&' : '' }} {{ dpl_command }} | o2-qc
=======
    {{ dpl_command }} | o2-dpl-raw-proxy
  _plain_cmdline: >-
    source /etc/profile.d/o2.sh && {{ len(extra_env_vars)>0 ? 'export ' + extra_env_vars + ' &&' : '' }} {{ dpl_command }} | o2-dpl-raw-proxy
>>>>>>> 27dbe988... Cpv noise calibration (#265):tasks/cpv-noise-calib-qc-internal-dpl-injected-dummy-sink.yaml
control:
  mode: "fairmq"
wants:
  cpu: 0.01
  memory: 1
bind:
command:
  shell: true
  log: "{{ log_task_output }}"
  env:
    - O2_DETECTOR={{ detector }}
    - O2_PARTITION={{ environment_id }}
  user: "{{ user }}"
  value: "{{ len(modulepath)>0 ? _module_cmdline : _plain_cmdline }}"
  arguments:
    - "-b"
    - "--exit-transition-timeout"
    - "'{{ exit_transition_timeout }}'"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'{{ session_id }}'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--shm-segment-size"
    - "'{{ shm_segment_size }}'"
    - "--shm-throw-bad-alloc"
    - "'{{ shm_throw_bad_alloc }}'"
    - "--resources-monitoring"
    - "'{{ resources_monitoring }}'"
    - "--id"
<<<<<<< HEAD:tasks/mid-full-qcmn-local-QcTaskMIDRaw-proxy.yaml
    - "'QcTaskMIDRaw-proxy'"
=======
    - "'internal-dpl-injected-dummy-sink'"
>>>>>>> 27dbe988... Cpv noise calibration (#265):tasks/cpv-noise-calib-qc-internal-dpl-injected-dummy-sink.yaml
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--dataspec"
    - "'x0:CPV/RAWDATA;dd:FLP/DISTSUBTIMEFRAME/0'"
    - "--early-forward-policy"
    - "'never'"
    - "--fairmq-ipc-prefix"
    - "'@'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'4'"
    - "--fairmq-send-buffer-size"
    - "'4'"
    - "--forwarding-destination"
    - "'drop'"
    - "--forwarding-policy"
    - "'dangling'"
<<<<<<< HEAD:tasks/mid-full-qcmn-local-QcTaskMIDRaw-proxy.yaml
    - "--host"
    - "'flp'"
    - "--labels"
    - "''"
    - "--local"
    - "--local-batch"
    - "''"
    - "--override-values"
    - "''"
=======
    - "--labels"
    - "''"
>>>>>>> 27dbe988... Cpv noise calibration (#265):tasks/cpv-noise-calib-qc-internal-dpl-injected-dummy-sink.yaml
    - "--pipeline"
    - "''"
    - "--proxy-name"
    - "'readout-proxy'"
    - "--readers"
    - "'1'"
<<<<<<< HEAD:tasks/mid-full-qcmn-local-QcTaskMIDRaw-proxy.yaml
    - "--remote-batch"
    - "''"
=======
>>>>>>> 27dbe988... Cpv noise calibration (#265):tasks/cpv-noise-calib-qc-internal-dpl-injected-dummy-sink.yaml
    - "--severity"
    - "'info'"
    - "--shm-allocation"
    - "'rbtree_best_fit'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-mlock-segment-on-creation"
    - "'false'"
    - "--shm-no-cleanup"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-zero-segment"
    - "'false'"
    - "--spawners"
    - "'1'"
    - "--stacktrace-on-signal"
<<<<<<< HEAD:tasks/mid-full-qcmn-local-QcTaskMIDRaw-proxy.yaml
    - "'simple'"
=======
    - "'all'"
>>>>>>> 27dbe988... Cpv noise calibration (#265):tasks/cpv-noise-calib-qc-internal-dpl-injected-dummy-sink.yaml
    - "--timeframes-rate-limit"
    - "'0'"
    - "--timeframes-rate-limit-ipcid"
    - "-1"
<<<<<<< HEAD:tasks/mid-full-qcmn-local-QcTaskMIDRaw-proxy.yaml
=======
    - "--timeframes-shm-limit"
    - "'0'"
>>>>>>> 27dbe988... Cpv noise calibration (#265):tasks/cpv-noise-calib-qc-internal-dpl-injected-dummy-sink.yaml
    - "--workflow-suffix"
    - "''"
