name: minimal-dpl-readout-proxy
defaults:
  user: flp
  detector: TST
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_readout-proxy_to_dpl-output-proxy
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "10"
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 Control-OCCPlugin &&
    o2-dpl-raw-proxy -b --session default --dataspec "x:{{ detector }}/RAWDATA;dd:FLP/DISTSUBTIMEFRAME/0" --readout-proxy '--channel-config "name=readout-proxy,type=pull,method=connect,address=ipc:///tmp/stf-builder-dpl-pipe-0,transport=shmem,rateLogging=1"' | o2-dpl-output-proxy -b --session default --dataspec "x:{{ detector }}/RAWDATA;dd:FLP/DISTSUBTIMEFRAME/0" --dpl-output-proxy '--channel-config "name=downstream,type=push,method=bind,address=ipc:///tmp/stf-pipe-0,rateLogging=1,transport=shmem"' | o2-dpl-raw-proxy
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "readout-proxy"
    - "--dataspec"
    - "'x:{{ detector }}/RAWDATA;dd:FLP/DISTSUBTIMEFRAME/0'"
    - "--log-color"
    - "false"
    - "--readers"
    - "1"
    - "--start-value-enumeration"
    - "0"
    - "--step-value-enumeration"
    - "1"
    - "--end-value-enumeration"
    - "-1"
    - "--session"
    - "default"
    - "--shm-monitor false"

