name: minimal-dpl-dpl-output-proxy
defaults:
  user: flp
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: downstream
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "10"
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 Control-OCCPlugin &&
    cat {{dpl_config}} | o2-dpl-output-proxy
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "dpl-output-proxy"
    - "--dataspec"
    - "'x:TST/RAWDATA;dd:FLP/DISTSUBTIMEFRAME/0'"
    - "--channel-config"
    - "name=downstream,type=push,method=bind,address=ipc:///tmp/stf-pipe-0,rateLogging=1,transport=shmem"
    - "--proxy-name"
    - "dpl-output-proxy"
    - "--log-color"
    - "false"
    - "--readers"
    - "1"
    - "--session"
    - "default"
    - "--shm-monitor false"

