name: o2-roc-cleanup
defaults:
  log_task_output: none
control:
  mode: basic
wants:
  cpu: 0.01
  memory: 3
command:
  log: "{{ log_task_output }}"
  shell: true
  user: root # o2-roc-cleanup must always run as root!
  value: yes | {{ o2_install_path }}/bin/o2-roc-cleanup
  arguments:
    - "--light"
    
# date > /etc/o2.d/last-roc-cleanup
