name: qc-postprocessing # read by workflow
defaults:
  pp_task_name: "ExampleTrend"
  pp_task_period: "10"
  user: flp
  log_task_output: none
control:
  mode: direct
wants:
  cpu: 0.15
  memory: 128
properties:
  "qcConfiguration": "{{ ToPtree(GetConfig('qc/postprocessing'), 'json') }}"
command:
  env: []
  log: "{{ log_task_output }}"
  shell: true
  user: "{{ user }}"
  arguments:
    - "--name"
    - "{{pp_task_name}}"
    - "--period"
    - "{{pp_task_period}}"
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load QualityControl Control-OCCPlugin &&
    o2-qc-run-postprocessing-occ
