name: readout-qc-dispatcher
defaults:
  qc_config_uri: consul-json://{{ consul_endpoint }}/o2/components/qc/readout_to_daqtask-{{ task_hostname }}
  user: flp
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_Dispatcher_to_QC-TASK-RUNNER-daqTask"
    type: "push"
    transport: shmem
    addressing: ipc
    rateLogging: "60"
command:
  shell: true
  value: >-
    eval `aliswmod load QualityControl Control-OCCPlugin` &&
    cat {{dpl_config}}| o2-qc
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--config"
    - "{{qc_config_uri}}"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "Dispatcher"
    - "--log-color"
    - "false"
    - "--readers"
    - "1"
    - "--session"
    - "default"
    - "--period-timer-stats"
    - "10000000"
    - "--severity"
    - "debug"
    - "--shm-monitor false"
