name: readout-internal-dpl-global-binary-file-sink
defaults:
  user: flp
  log_task_output: none
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
connect:
  - name: "from_QC-CHECK-RUNNER-Q4H0_to_internal-dpl-global-binary-file-sink"
    type: pull
    rateLogging: "60"
command:
  log: "{{ log_task_output }}"
  shell: true
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load QualityControl Control-OCCPlugin &&
    cat {{dpl_config}} | o2-qc-run-readout
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_dpl_url }}"
    - "--id"
    - "internal-dpl-global-binary-file-sink"
    - "--log-color"
    - "false"
    - "--readers"
    - "1"
    - "--session"
    - "default"
    - "--outfile"
    - "/dev/null"
    - "--shm-monitor false"
    - "--infologger-severity"
    - "{{infologger_severity}}"
    - "--infologger-mode"
    - "{{infologger_mode}}"
