name: roc-config-args
control:
  mode: basic
wants:
  cpu: 0.2
  memory: 256
defaults:
  rocConfigLinks: "0"
  rocConfigAllowRejection: "false"
  rocConfigClock: "LOCAL"
  rocConfigCruId: "0x0"
  rocConfigCrocId: "0x0"
  rocConfigDatapathMode: "PACKET"
  rocConfigDownstreamData: "CTP"
  rocConfigGbtMode: "GBT"
  rocConfigGbtMux: "TTC"
  rocConfigLoopback: "false"
  rocConfigPonUpstream: "false"
  rocConfigDynOffset: "false"
  rocConfigOnuAddress: "0"
  rocConfigForceConfig: "false"
  rocConfigBypassFwCheck: "false"
  rocConfigTriggerWindowSize: "1000"
  rocConfigNoGBT: "false"
  rocConfigUserLogic: "false"
  rocConfigRunStats: "false"
  rocConfigUserAndCommonLogic: "false"
  rocConfigNoTfDetection: "false"
  rocConfigTfLength: "256"
  rocConfigSystemId: "0x0"
  rocConfigFEEId: "0x0"
command: 
  env:
    - INFOLOGGER_MODE={{ infologger_mode }}
  shell: true
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH={{ modulepath }} module load ReadoutCard &&
    roc-config
  arguments:
    - "--id"
    - "{{ rocConfigId }}"
    - "--links"
    - "{{ rocConfigLinks }}"
    - "{{ rocConfigAllowRejection == 'true' ? '--allow-rejection' : '' }}"
    - "--clock"
    - "{{ rocConfigClock }}"
    - "--cru-id"
    - "{{ rocConfigCruId }}"
    - "--crorc-id"
    - "{{ rocConfigCrocId }}"
    - "--datapathmode"
    - "{{ rocConfigDatapathMode }}"
    - "--downstreamdata"
    - "{{ rocConfigDownstreamData }}"
    - "--gbtmode"
    - "{{ rocConfigGbtMode }}"
    - "--gbtmux"
    - "{{ rocConfigGbtMux }}"
    - "{{ rocConfigLoopback == 'true' ? '--loopback' : '' }}"
    - "{{ rocConfigPonUpstream == 'true' ? '--pon-upstream' : '' }}"
    - "{{ rocConfigDynOffset == 'true' ? '--dyn-offset' : '' }}"
    - "--onu-address"
    - "{{ rocConfigOnuAddress }}"
    - "{{ rocConfigForceConfig == 'true' ? '--force-config' : '' }}"
    - "{{ rocConfigBypassFwCheck == 'true' ? '--bypass-fw-check' : '' }}"
    - "--trigger-window-size"
    - "{{ rocConfigTriggerWindowSize }}"
    - "{{ rocConfigNoGBT == 'true' ? '--no-gbt' : '' }}"
    - "{{ rocConfigUserLogic == 'true' ? '--user-logic' : '' }}"
    - "{{ rocConfigRunStats == 'true' ? '--run-stats' : '' }}"
    - "{{ rocConfigUserAndCommonLogic == 'true' ? '--user-and-common-logic' : '' }}"
    - "{{ rocConfigNoTfDetection == 'true' ? '--no-tf-detection' : '' }}"
    - "--tf-length"
    - "{{ rocConfigTfLength }}"
    - "--system-id"
    - "{{ rocConfigSystemId }}"
    - "--fee-id"
    - "{{ rocConfigFEEId }}"
