name: roc-cleanup
control:
  mode: basic
wants:
  cpu: 0.01
  memory: 3
command:
  shell: true
  user: root # roc-cleanup must always run as root!
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load ReadoutCard &&
    yes | roc-cleanup
    
# date > /etc/o2.d/last-roc-cleanup
