name: shell-command
defaults:
  user: flp
  log_task_output: none
control:
  mode: basic
wants:
  cpu: 0.01
  memory: 3
command:
  log: "{{ log_task_output }}"
  shell: true
  user: "{{ user }}"
  value: >-
    {{ shell_command }}
