name: stfb-raw-proxy
defaults:
  stfb_dataspec: "B:TPC/RAWDATA"
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_readout-proxy_to_Dispatcher
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
command:
  shell: true
  value: >-
    eval `aliswmod load QualityControl Control-OCCPlugin` &&
    cat {{dpl_config}} | o2-dpl-raw-proxy
  user: flp
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "readout-proxy"
    - "--log-color"
    - "false"
    - "--dataspec"
    - "{{ stfb_dataspec }}"
    - "--readers"
    - "1"
    - "--start-value-enumeration"
    - "0"
    - "--step-value-enumeration"
    - "1"
    - "--end-value-enumeration"
    - "-1"
    - "--session"
    - "default"

