name: stfb-qc-check-runner
defaults:
  qc_config_uri: json:///home/flp/datadistribution.json
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_QC-CHECK-RUNNER-QcCheck_to_internal-dpl-global-binary-file-sink"
    type: "push"
    transport: shmem
    addressing: ipc
    rateLogging: "60"
command:
  shell: true
  value: >-
    eval `aliswmod load QualityControl Control-OCCPlugin` &&
    cat {{dpl_config}}| o2-qc
  user: flp
  arguments:
    - "-b"
    - "--config"
    - "{{qc_config_uri}}"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "QC-CHECK-RUNNER-QcCheck"
    - "--log-color"
    - "false"
    - "--readers"
    - "1"
    - "--session"
    - "default"
