name: tof-compressor-179-readout-proxy
defaults:
  log_task_output: none
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_readout-proxy_to_tof-compressor-0
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-1
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-10
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-11
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-12
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-13
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-14
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-15
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-16
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-17
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-18
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-19
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-2
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-20
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-21
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-22
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-23
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-24
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-25
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-26
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-27
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-28
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-29
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-3
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-30
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-31
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-32
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-33
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-4
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-5
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-6
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-7
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-8
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_tof-compressor-9
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
  - name: from_readout-proxy_to_dpl-output-proxy
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
command:
  shell: true
  log: "{{ log_task_output }}"
  user: "{{ user }}"
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    {{ dpl_command }} | o2-dpl-raw-proxy
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'default'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--shm-segment-size"
    - "'{{ shm_segment_size }}'"
    - "--shm-throw-bad-alloc"
    - "'{{ shm_throw_bad_alloc }}'"
    - "--id"
    - "'readout-proxy'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--dataspec"
    - "'x20:TOF/RAWDATA/20;x21:TOF/RAWDATA/21;x22:TOF/RAWDATA/22;x23:TOF/RAWDATA/23;x24:TOF/RAWDATA/24;x25:TOF/RAWDATA/25;x26:TOF/RAWDATA/26;x27:TOF/RAWDATA/27;x28:TOF/RAWDATA/28;x30:TOF/RAWDATA/30;x31:TOF/RAWDATA/31;x33:TOF/RAWDATA/33;x34:TOF/RAWDATA/34;x35:TOF/RAWDATA/35;x36:TOF/RAWDATA/36;x37:TOF/RAWDATA/37;x38:TOF/RAWDATA/38;x39:TOF/RAWDATA/39;x40:TOF/RAWDATA/40;x41:TOF/RAWDATA/41;x42:TOF/RAWDATA/42;x43:TOF/RAWDATA/43;x44:TOF/RAWDATA/44;x45:TOF/RAWDATA/45;x46:TOF/RAWDATA/46;x47:TOF/RAWDATA/47;x48:TOF/RAWDATA/48;x49:TOF/RAWDATA/49;x50:TOF/RAWDATA/50;x51:TOF/RAWDATA/51;x52:TOF/RAWDATA/52;x53:TOF/RAWDATA/53;x54:TOF/RAWDATA/54;x55:TOF/RAWDATA/55;dd:FLP/DISTSUBTIMEFRAME/0'"
    - "--fairmq-ipc-prefix"
    - "'/tmp'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'1000'"
    - "--fairmq-send-buffer-size"
    - "'1000'"
    - "--forwarding-destination"
    - "'drop'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--pipeline"
    - "''"
    - "--readers"
    - "'1'"
    - "--severity"
    - "'info'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-zero-segment"
    - "'false'"
    - "--stacktrace-on-signal"
    - "'all'"
    - "--workflow-suffix"
    - "''"
    - "--end-value-enumeration"
    - "-1"
    - "--start-value-enumeration"
    - "'0'"
    - "--step-value-enumeration"
    - "'1'"
