name: tof-compressor-readout-proxy
defaults:
  log_task_output: none
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_readout-proxy_to_tof-compressor-0
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: 10
  - name: from_readout-proxy_to_dpl-output-proxy
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: 10
command:
  shell: true
  log: "{{ log_task_output }}"
  user: "{{ user }}"
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    o2-dpl-raw-proxy -b --session default --dataspec "x:TOF/RAWDATA;dd/FLP/DISTSUBTIMEFRAME/0" --readout-proxy '--channel-config "name=readout-proxy,type=pull,method=connect,address=ipc:///tmp/stf-builder-dpl-pipe-0,transport=shmem,rateLogging=1"' | o2-tof-compressor -b --session default --tof-compressor-rdh-version 6 --tof-compressor-config "x:TOF/RAWDATA" | o2-dpl-output-proxy -b --session default --dataspec "A:TOF/CRAWDATA;dd:FLP/DISTSUBTIMEFRAME/0" --dpl-output-proxy '--channel-config "name=downstream,type=push,method=bind,address=ipc:///tmp/stf-pipe-0,rateLogging=1,transport=shmem"' | o2-dpl-raw-proxy
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'default'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--id"
    - "'readout-proxy'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--dataspec"
    - "'x:TOF/RAWDATA;dd/FLP/DISTSUBTIMEFRAME/0'"
    - "--fairmq-ipc-prefix"
    - "'/tmp/pkonopka'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'1000'"
    - "--fairmq-send-buffer-size"
    - "'1000'"
    - "--forwarding-destination"
    - "'file'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--pipeline"
    - "''"
    - "--readers"
    - "'1'"
    - "--severity"
    - "'info'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-segment-size"
    - "'2000000000'"
    - "--shm-throw-bad-alloc"
    - "'true'"
    - "--shm-zero-segment"
    - "'false'"
    - "--stacktrace-on-signal"
    - "'all'"
    - "--workflow-suffix"
    - "''"
    - "--end-value-enumeration"
    - "-1"
    - "--start-value-enumeration"
    - "'0'"
    - "--step-value-enumeration"
    - "'1'"
