name: tof-compressor-178-tof-compressor-8
defaults:
  log_task_output: none
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_tof-compressor-8_to_dpl-output-proxy
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
command:
  shell: true
  log: "{{ log_task_output }}"
  user: "{{ user }}"
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    {{ dpl_command }} | o2-tof-compressor
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'default'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--shm-segment-size"
    - "'{{ shm_segment_size }}'"
    - "--shm-throw-bad-alloc"
    - "'{{ shm_throw_bad_alloc }}'"
    - "--id"
    - "'tof-compressor-8'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--fairmq-ipc-prefix"
    - "'/tmp'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'1000'"
    - "--fairmq-send-buffer-size"
    - "'1000'"
    - "--forwarding-destination"
    - "'drop'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--pipeline"
    - "''"
    - "--readers"
    - "'1'"
    - "--severity"
    - "'info'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-zero-segment"
    - "'false'"
    - "--stacktrace-on-signal"
    - "'all'"
    - "--tof-compressor-config"
    - "'x0:TOF/RAWDATA/0,x1:TOF/RAWDATA/1,x2:TOF/RAWDATA/2,x3:TOF/RAWDATA/3,x4:TOF/RAWDATA/4,x5:TOF/RAWDATA/5,x6:TOF/RAWDATA/6,x7:TOF/RAWDATA/7,x8:TOF/RAWDATA/8,x9:TOF/RAWDATA/9,x10:TOF/RAWDATA/10,x11:TOF/RAWDATA/11,x12:TOF/RAWDATA/12,x13:TOF/RAWDATA/13,x14:TOF/RAWDATA/14,x15:TOF/RAWDATA/15,x16:TOF/RAWDATA/16,x17:TOF/RAWDATA/17,x18:TOF/RAWDATA/18,x19:TOF/RAWDATA/19,x56:TOF/RAWDATA/56,x57:TOF/RAWDATA/57,x58:TOF/RAWDATA/58,x59:TOF/RAWDATA/59,x60:TOF/RAWDATA/60,x61:TOF/RAWDATA/61,x62:TOF/RAWDATA/62,x63:TOF/RAWDATA/63,x64:TOF/RAWDATA/64,x65:TOF/RAWDATA/65,x66:TOF/RAWDATA/66,x67:TOF/RAWDATA/67,x68:TOF/RAWDATA/68,x69:TOF/RAWDATA/69,x70:TOF/RAWDATA/70,x71:TOF/RAWDATA/71'"
    - "--tof-compressor-output-desc"
    - "'CRAWDATA'"
    - "--tof-compressor-rdh-version"
    - "'6'"
    - "--workflow-suffix"
    - "''"
    - "--tof-compressor-output-buffer-size"
    - "'0'"
