name: tpc-idc-merger-internal-dpl-injected-dummy-sink
defaults:
  log_task_output: none
  exit_transition_timeout: 15
  _module_cmdline: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    {{ dpl_command }} | o2-dpl-raw-proxy
  _plain_cmdline: >-
    source /etc/profile.d/o2.sh && {{ len(extra_env_vars)>0 ? 'export ' + extra_env_vars + ' &&' : '' }} {{ dpl_command }} | o2-dpl-raw-proxy
control:
  mode: "fairmq"
wants:
  cpu: 0.01
  memory: 1
bind:
command:
  shell: true
  log: "{{ log_task_output }}"
  env:
    - O2_DETECTOR={{ detector }}
    - O2_PARTITION={{ environment_id }}
  user: "{{ user }}"
  value: "{{ len(modulepath)>0 ? _module_cmdline : _plain_cmdline }}"
  arguments:
    - "-b"
    - "--exit-transition-timeout"
    - "'{{ exit_transition_timeout }}'"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'{{ session_id }}'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--shm-segment-size"
    - "'{{ shm_segment_size }}'"
    - "--shm-throw-bad-alloc"
    - "'{{ shm_throw_bad_alloc }}'"
    - "--resources-monitoring"
    - "'{{ resources_monitoring }}'"
    - "--id"
    - "'internal-dpl-injected-dummy-sink'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--dataspec"
    - "'A:TPC/IDCGROUP/0;A:TPC/1DIDC/0;A:TPC/IDCGROUP/256;A:TPC/1DIDC/256;A:TPC/IDCGROUP/512;A:TPC/1DIDC/512;A:TPC/IDCGROUP/768;A:TPC/1DIDC/768;A:TPC/IDCGROUP/1024;A:TPC/1DIDC/1024;A:TPC/IDCGROUP/1280;A:TPC/1DIDC/1280;A:TPC/IDCGROUP/1536;A:TPC/1DIDC/1536;A:TPC/IDCGROUP/1792;A:TPC/1DIDC/1792;A:TPC/IDCGROUP/2048;A:TPC/1DIDC/2048;A:TPC/IDCGROUP/2304;A:TPC/1DIDC/2304;A:TPC/IDCGROUP/2560;A:TPC/1DIDC/2560;A:TPC/IDCGROUP/2816;A:TPC/1DIDC/2816;A:TPC/IDCGROUP/3072;A:TPC/1DIDC/3072;A:TPC/IDCGROUP/3328;A:TPC/1DIDC/3328;A:TPC/IDCGROUP/3584;A:TPC/1DIDC/3584;A:TPC/IDCGROUP/3840;A:TPC/1DIDC/3840;A:TPC/IDCGROUP/4096;A:TPC/1DIDC/4096;A:TPC/IDCGROUP/4352;A:TPC/1DIDC/4352;A:TPC/IDCGROUP/4608;A:TPC/1DIDC/4608;A:TPC/IDCGROUP/4864;A:TPC/1DIDC/4864;A:TPC/IDCGROUP/5120;A:TPC/1DIDC/5120;A:TPC/IDCGROUP/5376;A:TPC/1DIDC/5376;A:TPC/IDCGROUP/5632;A:TPC/1DIDC/5632;A:TPC/IDCGROUP/5888;A:TPC/1DIDC/5888;A:TPC/IDCGROUP/6144;A:TPC/1DIDC/6144;A:TPC/IDCGROUP/6400;A:TPC/1DIDC/6400;A:TPC/IDCGROUP/6656;A:TPC/1DIDC/6656;A:TPC/IDCGROUP/6912;A:TPC/1DIDC/6912;A:TPC/IDCGROUP/7168;A:TPC/1DIDC/7168;A:TPC/IDCGROUP/7424;A:TPC/1DIDC/7424;A:TPC/IDCGROUP/7680;A:TPC/1DIDC/7680;A:TPC/IDCGROUP/7936;A:TPC/1DIDC/7936;A:TPC/IDCGROUP/8192;A:TPC/1DIDC/8192;A:TPC/IDCGROUP/8448;A:TPC/1DIDC/8448;A:TPC/IDCGROUP/8704;A:TPC/1DIDC/8704;A:TPC/IDCGROUP/8960;A:TPC/1DIDC/8960;A:TPC/IDCGROUP/9216;A:TPC/1DIDC/9216;A:TPC/IDCGROUP/9472;A:TPC/1DIDC/9472;A:TPC/IDCGROUP/9728;A:TPC/1DIDC/9728;A:TPC/IDCGROUP/9984;A:TPC/1DIDC/9984;A:TPC/IDCGROUP/10240;A:TPC/1DIDC/10240;A:TPC/IDCGROUP/10496;A:TPC/1DIDC/10496;A:TPC/IDCGROUP/10752;A:TPC/1DIDC/10752;A:TPC/IDCGROUP/11008;A:TPC/1DIDC/11008;A:TPC/IDCGROUP/11264;A:TPC/1DIDC/11264;A:TPC/IDCGROUP/11520;A:TPC/1DIDC/11520;A:TPC/IDCGROUP/11776;A:TPC/1DIDC/11776;A:TPC/IDCGROUP/12032;A:TPC/1DIDC/12032;A:TPC/IDCGROUP/12288;A:TPC/1DIDC/12288;A:TPC/IDCGROUP/12544;A:TPC/1DIDC/12544;A:TPC/IDCGROUP/12800;A:TPC/1DIDC/12800;A:TPC/IDCGROUP/13056;A:TPC/1DIDC/13056;A:TPC/IDCGROUP/13312;A:TPC/1DIDC/13312;A:TPC/IDCGROUP/13568;A:TPC/1DIDC/13568;A:TPC/IDCGROUP/13824;A:TPC/1DIDC/13824;A:TPC/IDCGROUP/14080;A:TPC/1DIDC/14080;A:TPC/IDCGROUP/14336;A:TPC/1DIDC/14336;A:TPC/IDCGROUP/14592;A:TPC/1DIDC/14592;A:TPC/IDCGROUP/14848;A:TPC/1DIDC/14848;A:TPC/IDCGROUP/15104;A:TPC/1DIDC/15104;A:TPC/IDCGROUP/15360;A:TPC/1DIDC/15360;A:TPC/IDCGROUP/15616;A:TPC/1DIDC/15616;A:TPC/IDCGROUP/15872;A:TPC/1DIDC/15872;A:TPC/IDCGROUP/16128;A:TPC/1DIDC/16128;A:TPC/IDCGROUP/16384;A:TPC/1DIDC/16384;A:TPC/IDCGROUP/16640;A:TPC/1DIDC/16640;A:TPC/IDCGROUP/16896;A:TPC/1DIDC/16896;A:TPC/IDCGROUP/17152;A:TPC/1DIDC/17152;A:TPC/IDCGROUP/17408;A:TPC/1DIDC/17408;A:TPC/IDCGROUP/17664;A:TPC/1DIDC/17664;A:TPC/IDCGROUP/17920;A:TPC/1DIDC/17920;A:TPC/IDCGROUP/18176;A:TPC/1DIDC/18176;A:TPC/IDCGROUP/18432;A:TPC/1DIDC/18432;A:TPC/IDCGROUP/18688;A:TPC/1DIDC/18688;A:TPC/IDCGROUP/18944;A:TPC/1DIDC/18944;A:TPC/IDCGROUP/19200;A:TPC/1DIDC/19200;A:TPC/IDCGROUP/19456;A:TPC/1DIDC/19456;A:TPC/IDCGROUP/19712;A:TPC/1DIDC/19712;A:TPC/IDCGROUP/19968;A:TPC/1DIDC/19968;A:TPC/IDCGROUP/20224;A:TPC/1DIDC/20224;A:TPC/IDCGROUP/20480;A:TPC/1DIDC/20480;A:TPC/IDCGROUP/20736;A:TPC/1DIDC/20736;A:TPC/IDCGROUP/20992;A:TPC/1DIDC/20992;A:TPC/IDCGROUP/21248;A:TPC/1DIDC/21248;A:TPC/IDCGROUP/21504;A:TPC/1DIDC/21504;A:TPC/IDCGROUP/21760;A:TPC/1DIDC/21760;A:TPC/IDCGROUP/22016;A:TPC/1DIDC/22016;A:TPC/IDCGROUP/22272;A:TPC/1DIDC/22272;A:TPC/IDCGROUP/22528;A:TPC/1DIDC/22528;A:TPC/IDCGROUP/22784;A:TPC/1DIDC/22784;A:TPC/IDCGROUP/23040;A:TPC/1DIDC/23040;A:TPC/IDCGROUP/23296;A:TPC/1DIDC/23296;A:TPC/IDCGROUP/23552;A:TPC/1DIDC/23552;A:TPC/IDCGROUP/23808;A:TPC/1DIDC/23808;A:TPC/IDCGROUP/24064;A:TPC/1DIDC/24064;A:TPC/IDCGROUP/24320;A:TPC/1DIDC/24320;A:TPC/IDCGROUP/24576;A:TPC/1DIDC/24576;A:TPC/IDCGROUP/24832;A:TPC/1DIDC/24832;A:TPC/IDCGROUP/25088;A:TPC/1DIDC/25088;A:TPC/IDCGROUP/25344;A:TPC/1DIDC/25344;A:TPC/IDCGROUP/25600;A:TPC/1DIDC/25600;A:TPC/IDCGROUP/25856;A:TPC/1DIDC/25856;A:TPC/IDCGROUP/26112;A:TPC/1DIDC/26112;A:TPC/IDCGROUP/26368;A:TPC/1DIDC/26368;A:TPC/IDCGROUP/26624;A:TPC/1DIDC/26624;A:TPC/IDCGROUP/26880;A:TPC/1DIDC/26880;A:TPC/IDCGROUP/27136;A:TPC/1DIDC/27136;A:TPC/IDCGROUP/27392;A:TPC/1DIDC/27392;A:TPC/IDCGROUP/27648;A:TPC/1DIDC/27648;A:TPC/IDCGROUP/27904;A:TPC/1DIDC/27904;A:TPC/IDCGROUP/28160;A:TPC/1DIDC/28160;A:TPC/IDCGROUP/28416;A:TPC/1DIDC/28416;A:TPC/IDCGROUP/28672;A:TPC/1DIDC/28672;A:TPC/IDCGROUP/28928;A:TPC/1DIDC/28928;A:TPC/IDCGROUP/29184;A:TPC/1DIDC/29184;A:TPC/IDCGROUP/29440;A:TPC/1DIDC/29440;A:TPC/IDCGROUP/29696;A:TPC/1DIDC/29696;A:TPC/IDCGROUP/29952;A:TPC/1DIDC/29952;A:TPC/IDCGROUP/30208;A:TPC/1DIDC/30208;A:TPC/IDCGROUP/30464;A:TPC/1DIDC/30464;A:TPC/IDCGROUP/30720;A:TPC/1DIDC/30720;A:TPC/IDCGROUP/30976;A:TPC/1DIDC/30976;A:TPC/IDCGROUP/31232;A:TPC/1DIDC/31232;A:TPC/IDCGROUP/31488;A:TPC/1DIDC/31488;A:TPC/IDCGROUP/31744;A:TPC/1DIDC/31744;A:TPC/IDCGROUP/32000;A:TPC/1DIDC/32000;A:TPC/IDCGROUP/32256;A:TPC/1DIDC/32256;A:TPC/IDCGROUP/32512;A:TPC/1DIDC/32512;A:TPC/IDCGROUP/32768;A:TPC/1DIDC/32768;A:TPC/IDCGROUP/33024;A:TPC/1DIDC/33024;A:TPC/IDCGROUP/33280;A:TPC/1DIDC/33280;A:TPC/IDCGROUP/33536;A:TPC/1DIDC/33536;A:TPC/IDCGROUP/33792;A:TPC/1DIDC/33792;A:TPC/IDCGROUP/34048;A:TPC/1DIDC/34048;A:TPC/IDCGROUP/34304;A:TPC/1DIDC/34304;A:TPC/IDCGROUP/34560;A:TPC/1DIDC/34560;A:TPC/IDCGROUP/34816;A:TPC/1DIDC/34816;A:TPC/IDCGROUP/35072;A:TPC/1DIDC/35072;A:TPC/IDCGROUP/35328;A:TPC/1DIDC/35328;A:TPC/IDCGROUP/35584;A:TPC/1DIDC/35584;A:TPC/IDCGROUP/35840;A:TPC/1DIDC/35840;A:TPC/IDCGROUP/36096;A:TPC/1DIDC/36096;A:TPC/IDCGROUP/36352;A:TPC/1DIDC/36352;A:TPC/IDCGROUP/36608;A:TPC/1DIDC/36608;A:TPC/IDCGROUP/36864;A:TPC/1DIDC/36864;A:TPC/IDCGROUP/37120;A:TPC/1DIDC/37120;A:TPC/IDCGROUP/37376;A:TPC/1DIDC/37376;A:TPC/IDCGROUP/37632;A:TPC/1DIDC/37632;A:TPC/IDCGROUP/37888;A:TPC/1DIDC/37888;A:TPC/IDCGROUP/38144;A:TPC/1DIDC/38144;A:TPC/IDCGROUP/38400;A:TPC/1DIDC/38400;A:TPC/IDCGROUP/38656;A:TPC/1DIDC/38656;A:TPC/IDCGROUP/38912;A:TPC/1DIDC/38912;A:TPC/IDCGROUP/39168;A:TPC/1DIDC/39168;A:TPC/IDCGROUP/39424;A:TPC/1DIDC/39424;A:TPC/IDCGROUP/39680;A:TPC/1DIDC/39680;A:TPC/IDCGROUP/39936;A:TPC/1DIDC/39936;A:TPC/IDCGROUP/40192;A:TPC/1DIDC/40192;A:TPC/IDCGROUP/40448;A:TPC/1DIDC/40448;A:TPC/IDCGROUP/40704;A:TPC/1DIDC/40704;A:TPC/IDCGROUP/40960;A:TPC/1DIDC/40960;A:TPC/IDCGROUP/41216;A:TPC/1DIDC/41216;A:TPC/IDCGROUP/41472;A:TPC/1DIDC/41472;A:TPC/IDCGROUP/41728;A:TPC/1DIDC/41728;A:TPC/IDCGROUP/41984;A:TPC/1DIDC/41984;A:TPC/IDCGROUP/42240;A:TPC/1DIDC/42240;A:TPC/IDCGROUP/42496;A:TPC/1DIDC/42496;A:TPC/IDCGROUP/42752;A:TPC/1DIDC/42752;A:TPC/IDCGROUP/43008;A:TPC/1DIDC/43008;A:TPC/IDCGROUP/43264;A:TPC/1DIDC/43264;A:TPC/IDCGROUP/43520;A:TPC/1DIDC/43520;A:TPC/IDCGROUP/43776;A:TPC/1DIDC/43776;A:TPC/IDCGROUP/44032;A:TPC/1DIDC/44032;A:TPC/IDCGROUP/44288;A:TPC/1DIDC/44288;A:TPC/IDCGROUP/44544;A:TPC/1DIDC/44544;A:TPC/IDCGROUP/44800;A:TPC/1DIDC/44800;A:TPC/IDCGROUP/45056;A:TPC/1DIDC/45056;A:TPC/IDCGROUP/45312;A:TPC/1DIDC/45312;A:TPC/IDCGROUP/45568;A:TPC/1DIDC/45568;A:TPC/IDCGROUP/45824;A:TPC/1DIDC/45824'"
    - "--early-forward-policy"
    - "'never'"
    - "--fairmq-ipc-prefix"
    - "'@'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'4'"
    - "--fairmq-send-buffer-size"
    - "'4'"
    - "--forwarding-destination"
    - "'drop'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--labels"
    - "'tpc-idc-merger-proxy:ecs-preserve-raw-channels'"
    - "--pipeline"
    - "''"
    - "--proxy-name"
    - "'tpc-idc-merger-proxy'"
    - "--readers"
    - "'1'"
    - "--severity"
    - "'warning'"
    - "--shm-allocation"
    - "'rbtree_best_fit'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-mlock-segment-on-creation"
    - "'false'"
    - "--shm-no-cleanup"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-zero-segment"
    - "'false'"
    - "--spawners"
    - "'1'"
    - "--stacktrace-on-signal"
    - "'simple'"
    - "--timeframes-rate-limit"
    - "'0'"
    - "--timeframes-rate-limit-ipcid"
    - "-1"
    - "--timeframes-shm-limit"
    - "'0'"
    - "--workflow-suffix"
    - "''"
