name: o2-roc-config
defaults:
  roc_config_uri_enabled: "true"
  log_task_output: none
roles:
  - name: host-{{ it }}
    for:
      range: "{{ hosts }}"
      var: it
    constraints:
      - attribute: machine_id
        value: "{{ it }}"
    roles:
      - name: roc-config-uri
        enabled: "{{roc_config_uri_enabled == 'true'}}"
        task:
          load: "roc-config-uri"
          timeout: 10s
      - name: roc-config-args
        enabled: "{{roc_config_uri_enabled != 'true'}}"
        task:
          load: "roc-config-args"
          timeout: 10s
